export const JobMatches = [
  {
    id: 1,
    company: "Google",
    role: "SDE Intern",
    matchPercentage: 85,
    progressWidth: "85%",
  },
  {
    id: 2,
    company: "Microsoft",
    role: "Software Engineer Intern",
    matchPercentage: 78,
    progressWidth: "78%",
  },
  {
    id: 3,
    company: "Amazon",
    role: "Backend Developer Intern",
    matchPercentage: 72,
    progressWidth: "72%",
  },
  {
    id: 4,
    company: "Meta",
    role: "Frontend Engineer Intern",
    matchPercentage: 88,
    progressWidth: "88%",
  },
  {
    id: 5,
    company: "Netflix",
    role: "Full Stack Intern",
    matchPercentage: 81,
    progressWidth: "81%",
  },
  {
    id: 6,
    company: "Adobe",
    role: "UI Engineer Intern",
    matchPercentage: 75,
    progressWidth: "75%",
  },
  {
    id: 7,
    company: "Tesla",
    role: "Software Intern",
    matchPercentage: 69,
    progressWidth: "69%",
  },
  {
    id: 8,
    company: "Uber",
    role: "SDE Intern",
    matchPercentage: 83,
    progressWidth: "83%",
  },
  {
    id: 9,
    company: "Flipkart",
    role: "Backend Engineer Intern",
    matchPercentage: 76,
    progressWidth: "76%",
  },
];
